# Generated by Django 4.1 on 2024-03-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0003_afmeldingsliste_name_substitutliste_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afmeldingsliste',
            name='framed_users',
        ),
        migrations.AddField(
            model_name='afmeldingsliste',
            name='afbud',
            field=models.TextField(default='Afbud'),
        ),
        migrations.AlterField(
            model_name='substitutliste',
            name='substitutes',
            field=models.ManyToManyField(related_name='substitutes', to='club_management.customuser'),
        ),
    ]
