# Generated by Django 4.1 on 2024-03-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0004_remove_afmeldingsliste_framed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='days_available',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
