# Generated by Django 4.1 on 2024-03-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0005_customuser_days_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='days_available',
        ),
        migrations.AddField(
            model_name='customuser',
            name='days_available',
            field=models.ManyToManyField(blank=True, related_name='available_users', to='club_management.day'),
        ),
    ]
