# Generated by Django 4.1 on 2024-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0010_alter_substitutliste_substitutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='unavailable_days',
            field=models.ManyToManyField(blank=True, related_name='unavailable_users', to='club_management.unavailableday'),
        ),
    ]
