# Generated by Django 4.1 on 2024-03-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0011_unavailableday_customuser_unavailable_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailableday',
            name='name',
        ),
        migrations.AddField(
            model_name='unavailableday',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='unavailableday',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_management.customuser'),
        ),
    ]
