# Generated by Django 4.1 on 2024-03-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0012_remove_unavailableday_name_unavailableday_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unavailable_days',
        ),
        migrations.DeleteModel(
            name='UnavailableDay',
        ),
    ]
