# Generated by Django 4.1 on 2024-03-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0014_remove_dayresponsibility_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayresponsibility',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
