# Generated by Django 4.1 on 2024-03-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0015_alter_dayresponsibility_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayresponsibility',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.day'),
        ),
    ]
