# Generated by Django 4.1 on 2024-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0016_alter_dayresponsibility_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Substitutter', 'Substitutter')], max_length=20),
        ),
    ]
