# Generated by Django 4.1 on 2024-03-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Uger'},
        ),
    ]
