# Generated by Django 4.1 on 2024-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0020_configuration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitutliste',
            name='substitutes',
        ),
        migrations.AddField(
            model_name='substitutliste',
            name='substitutes_text',
            field=models.TextField(blank=True),
        ),
    ]
