# Generated by Django 4.1 on 2024-04-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_management", "0022_day_unavailable_customuser_days_unavailable"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnavailableDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="days_unavailable",
        ),
        migrations.DeleteModel(
            name="Day_unavailable",
        ),
        migrations.AddField(
            model_name="customuser",
            name="unavailable_dates",
            field=models.ManyToManyField(
                related_name="users", to="club_management.unavailabledate"
            ),
        ),
    ]
