# Generated by Django 4.2.15 on 2024-08-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0024_remove_customuser_unavailable_dates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Række',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Rækker',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='row',
        ),
        migrations.AddField(
            model_name='customuser',
            name='række',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_management.række'),
        ),
    ]
