# Generated by Django 4.2.15 on 2024-08-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0025_række_remove_customuser_row_customuser_række'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_note',
            field=models.TextField(blank=True, help_text='Enter a custom note for the user.', null=True),
        ),
    ]
