# Generated by Django 4.2.15 on 2024-08-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0029_usersubstitutassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unavailable_days',
        ),
    ]
