# Generated by Django 4.2.15 on 2024-08-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0030_remove_customuser_unavailable_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitutliste',
            name='substitutes_text',
        ),
    ]
