# Generated by Django 4.2.15 on 2024-08-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0031_remove_substitutliste_substitutes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Taken', 'Taken')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='substitutliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.substitutliste'),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.customuser'),
        ),
    ]
