# Generated by Django 4.2.15 on 2024-08-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0034_alter_day_options_day_danish_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='danish_name',
            new_name='english_name',
        ),
    ]
