# Generated by Django 4.2.15 on 2024-08-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0035_rename_danish_name_day_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Ledig', 'Ledig'), ('Optaget', 'Optaget'), ('Fraværende', 'Fraværende')], default='Ledig', max_length=20),
        ),
    ]
