# Generated by Django 4.2.15 on 2024-08-29 19:55

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0037_alter_usersubstitutassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubstitutassignment',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Taken', 'Taken'), ('Fraværende', 'Fraværende')], default='Free', max_length=20),
        ),
    ]
