# Generated by Django 4.2.15 on 2024-08-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0038_alter_usersubstitutassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Navn'),
        ),
    ]
