# Generated by Django 4.2.15 on 2024-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0039_alter_customuser_phone_number_alter_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitutliste',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
