# Generated by Django 4.2.15 on 2024-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0040_alter_substitutliste_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitutliste',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
