# Generated by Django 4.2.15 on 2024-08-29 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0041_alter_substitutliste_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Ledig', 'Ledig'), ('Optaget', 'Optaget'), ('Fraværende', 'Fraværende')], default='Ledig', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='substitutliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='club_management.substitutliste'),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitut_assignments', to='club_management.customuser'),
        ),
    ]
