# Generated by Django 4.2.15 on 2024-08-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0042_alter_usersubstitutassignment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={},
        ),
        migrations.RemoveField(
            model_name='day',
            name='english_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=12121212, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Taken', 'Taken')], default='Free', max_length=10),
        ),
    ]
