# Generated by Django 4.2.15 on 2024-08-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0043_alter_day_options_remove_day_english_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Dag', 'verbose_name_plural': 'Dage'},
        ),
        migrations.AlterModelOptions(
            name='usersubstitutassignment',
            options={'verbose_name': 'Substitutliste tildelinger', 'verbose_name_plural': 'Substitutliste tildelinger'},
        ),
        migrations.AddField(
            model_name='day',
            name='english_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Ledig', 'Ledig'), ('Optaget', 'Optaget'), ('Fraværende', 'Fraværende')], default='Ledig', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='substitutliste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.substitutliste'),
        ),
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.customuser'),
        ),
    ]
