# Generated by Django 4.2.15 on 2024-08-29 21:40

from django.db import migrations

def update_day_names(apps, schema_editor):
    Day = apps.get_model('club_management', 'Day')
    day_mapping = {
        'Mandag': 'Monday',
        'Tirsdag': 'Tuesday',
        'Onsdag': 'Wednesday',
        'Torsdag': 'Thursday',
        'Fredag': 'Friday',
        'Lørdag': 'Saturday',
        'Søndag': 'Sunday'
    }
    for danish, english in day_mapping.items():
        Day.objects.filter(name=danish).update(name=english)

class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0044_alter_day_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_day_names),
    ]
