# Generated by Django 4.2.15 on 2024-08-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0045_auto_20240829_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
        migrations.RemoveField(
            model_name='day',
            name='english_name',
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
