# Generated by Django 4.2.15 on 2024-08-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0046_alter_day_options_remove_day_english_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubstitutassignment',
            name='status',
            field=models.CharField(choices=[('Ledig', 'Ledig'), ('Optaget', 'Optaget'), ('Fraværende', 'Fraværende')], default='Free', max_length=20),
        ),
    ]
