# Generated by Django 4.2.15 on 2024-08-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0047_alter_usersubstitutassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
