# Generated by Django 5.1 on 2024-09-01 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_management", "0050_usersubstitutassignment_reservationsnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="afmeldingsliste",
            name="day",
            field=models.DateField(verbose_name="Dag"),
        ),
        migrations.AlterField(
            model_name="afmeldingsliste",
            name="name",
            field=models.CharField(
                default="unknown", max_length=100, verbose_name="Navn"
            ),
        ),
        migrations.AlterField(
            model_name="afmeldingsliste",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="club_management.week",
                verbose_name="Uge",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(
                default="Forsidetekst", max_length=100, verbose_name="Navn"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="welcome_text",
            field=models.TextField(verbose_name="Velkomsttekst"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="custom_note",
            field=models.TextField(
                blank=True,
                help_text="Note til substitut (Vises på forsiden).",
                null=True,
                verbose_name="Note til substitut",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Telefonnummer"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("Substitutter", "Substitutter")],
                max_length=20,
                verbose_name="Brugertype",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Brugernavn"
            ),
        ),
        migrations.AlterField(
            model_name="dayresponsibility",
            name="coordinator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ansvarlig",
            ),
        ),
        migrations.AlterField(
            model_name="dayresponsibility",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="club_management.day",
                verbose_name="Dag",
            ),
        ),
        migrations.AlterField(
            model_name="række",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Navn"),
        ),
        migrations.AlterField(
            model_name="substitutliste",
            name="day",
            field=models.DateField(verbose_name="Dag"),
        ),
        migrations.AlterField(
            model_name="substitutliste",
            name="deadline",
            field=models.DateTimeField(verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="substitutliste",
            name="name",
            field=models.CharField(
                default="unknown", max_length=100, verbose_name="Navn"
            ),
        ),
        migrations.AlterField(
            model_name="substitutliste",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="club_management.week",
                verbose_name="Uge",
            ),
        ),
        migrations.AlterField(
            model_name="usersubstitutassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="club_management.customuser",
                verbose_name="Substitut",
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Ugenummer"),
        ),
    ]
