# Generated by Django 5.1 on 2024-09-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "club_management",
            "0051_alter_afmeldingsliste_day_alter_afmeldingsliste_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="afmeldingsliste",
            name="week",
        ),
    ]
