# Generated by Django 5.1 on 2024-09-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_management", "0052_remove_afmeldingsliste_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="afmeldingsliste",
            name="afbud",
            field=models.TextField(blank=True),
        ),
    ]
