# Generated by Django 5.1 on 2024-10-05 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_management", "0053_alter_afmeldingsliste_afbud"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        default="Unknown", max_length=100, verbose_name="Navn"
                    ),
                ),
                (
                    "makker",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Makker"
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(max_length=100, verbose_name="Kontaktinformation"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="configuration",
            options={
                "verbose_name": "Brugerdefineret tekst",
                "verbose_name_plural": "Brugerdefineret tekst",
            },
        ),
        migrations.AddField(
            model_name="configuration",
            name="afmeldingslister_text",
            field=models.TextField(
                default="Default text", verbose_name="Afmeldingslister Tekst"
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="substitutlister_text",
            field=models.TextField(
                default="Default text", verbose_name="Substitutlister Tekst"
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="tilmeldingslister_text",
            field=models.TextField(
                default="Default text", verbose_name="Tilmeldingslister Tekst"
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="name",
            field=models.CharField(
                default="Brugerdefineret tekst", max_length=100, verbose_name="Navn"
            ),
        ),
        migrations.CreateModel(
            name="Tilmeldingsliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="unknown", max_length=100, verbose_name="Navn"
                    ),
                ),
                ("day", models.DateField(verbose_name="Dag")),
                ("deadline", models.DateTimeField(verbose_name="Deadline")),
                (
                    "antal_par",
                    models.IntegerField(default=24, verbose_name="Antal Par"),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ansvarlig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tilmeldingsliste",
                "verbose_name_plural": "Tilmeldingslister",
            },
        ),
        migrations.CreateModel(
            name="TilmeldingslistePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navn",
                    models.CharField(
                        blank=True,
                        default="Unknown",
                        max_length=100,
                        null=True,
                        verbose_name="Navn",
                    ),
                ),
                (
                    "makker",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Makker"
                    ),
                ),
                (
                    "telefonnummer",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefonnummer",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "på_venteliste",
                    models.BooleanField(default=False, verbose_name="På Venteliste"),
                ),
                (
                    "parnummer",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Parnummer"
                    ),
                ),
                (
                    "is_single",
                    models.BooleanField(default=False, verbose_name="Uden makker"),
                ),
                (
                    "tilmeldingsliste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="club_management.tilmeldingsliste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tilmeldingsliste Par",
                "verbose_name_plural": "Tilmeldingsliste Par",
            },
        ),
    ]
