# Generated by Django 4.2.24 on 2025-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0054_pair_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Navn'),
        ),
    ]
