# Generated by Django 4.2.24 on 2025-09-08 11:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('club_management', '0055_alter_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='afmeldingslister_text',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Afmeldingslister Tekst'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='substitutlister_text',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Substitutlister Tekst'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='tilmeldingslister_text',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Tilmeldingslister Tekst'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='welcome_text',
            field=wagtail.fields.RichTextField(verbose_name='Velkomsttekst'),
        ),
        migrations.CreateModel(
            name='SiteTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', wagtail.fields.RichTextField(blank=True, verbose_name='Velkomsttekst')),
                ('substitutlister_text', wagtail.fields.RichTextField(blank=True, verbose_name='Substitutlister Tekst')),
                ('afmeldingslister_text', wagtail.fields.RichTextField(blank=True, verbose_name='Afmeldingslister Tekst')),
                ('tilmeldingslister_text', wagtail.fields.RichTextField(blank=True, verbose_name='Tilmeldingslister Tekst')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Website tekster',
            },
        ),
    ]
